import { FileText, Download, Trash2 } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Badge } from "@/components/ui/badge"

const recentReports = [
  {
    id: "1",
    name: "Q3 Compliance Summary",
    type: "Compliance",
    generatedBy: "John Doe",
    date: "Oct 15, 2023",
    status: "Ready",
  },
  {
    id: "2",
    name: "Tech Solutions Ltd - File",
    type: "Client File",
    generatedBy: "Jane Smith",
    date: "Oct 14, 2023",
    status: "Ready",
  },
  {
    id: "3",
    name: "Expiring Documents List",
    type: "Inventory",
    generatedBy: "John Doe",
    date: "Oct 12, 2023",
    status: "Ready",
  },
]

export function RecentReports() {
  return (
    <div className="space-y-4">
      <h3 className="text-lg font-medium">Recently Generated</h3>
      <div className="rounded-md border">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Report Name</TableHead>
              <TableHead>Type</TableHead>
              <TableHead>Generated By</TableHead>
              <TableHead>Date</TableHead>
              <TableHead>Status</TableHead>
              <TableHead className="text-right">Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {recentReports.map((report) => (
              <TableRow key={report.id}>
                <TableCell className="font-medium">
                  <div className="flex items-center gap-2">
                    <FileText className="h-4 w-4 text-muted-foreground" />
                    {report.name}
                  </div>
                </TableCell>
                <TableCell>{report.type}</TableCell>
                <TableCell>{report.generatedBy}</TableCell>
                <TableCell>{report.date}</TableCell>
                <TableCell>
                  <Badge variant="outline" className="bg-green-50 text-green-700 border-green-200">
                    {report.status}
                  </Badge>
                </TableCell>
                <TableCell className="text-right">
                  <div className="flex justify-end gap-2">
                    <Button variant="ghost" size="icon" className="h-8 w-8">
                      <Download className="h-4 w-4" />
                    </Button>
                    <Button variant="ghost" size="icon" className="h-8 w-8 text-destructive hover:text-destructive">
                      <Trash2 className="h-4 w-4" />
                    </Button>
                  </div>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>
    </div>
  )
}
