import type { AuditLogEntry } from "@/types"

export const MOCK_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: "log-1",
    action: "Created Client",
    entityType: "Client",
    entityName: "Guyana Tech Solutions",
    entityId: "cli-123",
    user: {
      name: "John Doe",
      email: "john@gcmc.gy",
      avatar: "/avatars/01.png",
    },
    timestamp: "2023-10-26T10:30:00Z",
    details: "Created new client profile with Business Registration service",
    ipAddress: "192.168.1.45",
    status: "Success",
  },
  {
    id: "log-2",
    action: "Uploaded Document",
    entityType: "Document",
    entityName: "TIN Certificate.pdf",
    entityId: "doc-456",
    user: {
      name: "Sarah Smith",
      email: "sarah@gcmc.gy",
      avatar: "/avatars/02.png",
    },
    timestamp: "2023-10-26T11:15:00Z",
    details: "Uploaded TIN Certificate for ABC Corp",
    ipAddress: "192.168.1.42",
    status: "Success",
  },
  {
    id: "log-3",
    action: "Failed Login Attempt",
    entityType: "User",
    entityName: "admin@gcmc.gy",
    entityId: "usr-789",
    user: {
      name: "Unknown",
      email: "admin@gcmc.gy",
    },
    timestamp: "2023-10-26T09:00:00Z",
    details: "Invalid password attempt 3 times",
    ipAddress: "203.0.113.5",
    status: "Warning",
  },
  {
    id: "log-4",
    action: "Submitted Filing",
    entityType: "Filing",
    entityName: "VAT Return - Q3 2023",
    entityId: "fil-101",
    user: {
      name: "Mike Jones",
      email: "mike@kaj.gy",
      avatar: "/avatars/03.png",
    },
    timestamp: "2023-10-25T14:20:00Z",
    details: "Submitted VAT Return to GRA Portal",
    ipAddress: "192.168.1.50",
    status: "Success",
  },
  {
    id: "log-5",
    action: "Deleted Document",
    entityType: "Document",
    entityName: "Old Contract.pdf",
    entityId: "doc-999",
    user: {
      name: "John Doe",
      email: "john@gcmc.gy",
      avatar: "/avatars/01.png",
    },
    timestamp: "2023-10-25T16:45:00Z",
    details: "Removed outdated contract file",
    ipAddress: "192.168.1.45",
    status: "Success",
  },
  {
    id: "log-6",
    action: "System Backup",
    entityType: "System",
    entityName: "Daily Backup",
    entityId: "sys-backup-001",
    user: {
      name: "System",
      email: "system@gcmc.gy",
    },
    timestamp: "2023-10-26T00:00:00Z",
    details: "Automated daily database backup completed",
    ipAddress: "localhost",
    status: "Success",
  },
  {
    id: "log-7",
    action: "Updated Compliance Score",
    entityType: "Client",
    entityName: "Retail Plus Inc",
    entityId: "cli-456",
    user: {
      name: "System",
      email: "system@gcmc.gy",
    },
    timestamp: "2023-10-25T08:00:00Z",
    details: "Auto-calculated score dropped due to overdue filing",
    ipAddress: "localhost",
    status: "Warning",
  },
]
